create table BANK_DETAILS (
    ID VARCHAR(255) NOT NULL,
    ACCOUNT_NO VARCHAR(255) NOT NULL,
     ACCOUNT_TYPE VARCHAR(255) NOT NULL,
      BALANCE   INTEGER NOT NULL,
        NAME  VARCHAR(255) NOT NULL,
        primary key(ID)
);